<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 C:\Users\Nicholas\Documents\zero\realcan\static\models\Dragonfruit_Full_Sculpt.glb --root /models/ --printwidth 120 --precision 2
-->

<script>
  import { Group } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  export const ref = new Group()

  const gltf = useGltf('/models/Dragonfruit_Full_Sculpt.glb')

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Mesh
      geometry={gltf.nodes.Dragonfruit_Full_Sculpt_Baked.geometry}
      material={gltf.materials['Dragonfruit_Full_Sculpt_Baked.001']}
      position={[0, 1.74, 0]}
      rotation={[1.38, 0.23, -1.73]}
      scale={1.03}
    />
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
