<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 C:\Users\Nicholas\Documents\zero\realcan\static\models\Gleem_Can_DragonFruitMango.glb --root /models/ --printwidth 120 --precision 2
-->

<script>
  import { Group, LoadingManager, MeshPhysicalMaterial } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  export const ref = new Group()

  const gltf = useGltf('/models/Gleem_Can_DragonFruitMango.glb')
  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    {#each Object.entries(gltf.materials) as [label, material]}
      {material.envMapIntensity=0.75}
    {/each}
    <T.Mesh
      geometry={gltf.nodes.Gleem_Can_DragonFruitMango_Baked.geometry}
      material={gltf.materials['Gleem_Can_DragonFruitMango_Baked.001']}
      position={[0, 2.61, 0]}
      scale={[1.07, 1.1, 1.07]}
    >
    
    </T.Mesh>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
