<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 C:\Users\Nicholas\Documents\zero\realcan\static\models\WhitePeach_Full_Leaf.005.glb --root /models/ --printwidth 120 --precision 2
-->

<script>
  import { Group } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  export const ref = new Group()

  const gltf = useGltf('/models/WhitePeach_Full_Leaf.005.glb')

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Mesh
      geometry={gltf.nodes.WhitePeach_Full_Leaf005_Baked.geometry}
      material={gltf.materials['WhitePeach_Full_Leaf.005_Baked']}
      position={[-1.12, 1.3, 0.54]}
      rotation={[2.17, 0.36, 0.77]}
      scale={1.88}
    />
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
